name: Terraform Apply

on:
  push:
    branches:
      - main
    paths:
      - 'terraform_up_running/chapter_6/ec2-iam-role/**'

permissions:
  id-token: write
  contents: read

jobs:
  TerraformApply:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # Autenticarse a AWS usando OIDC
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      # Instalar Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6
          terraform_wrapper: false

      # Inicializar y aplicar Terraform
      - name: Terraform Init & Apply
        working-directory: terraform_up_running/chapter_6/ec2-iam-role
        run: |
          terraform init -input=false
          terraform apply -auto-approve -input=false
